### ISSUE TITLE
Does not account for non-Article-space links

### ISSUE THREAD

**Issue by hughlilly** [wikimedia/wikipedia-preview#152]
As can be seen in the screenshot below from the paragraph headed "Steps Involved" on the Diff post "[Synchronising Wikidata and Wikipedia: an Outreachy project](https://diff.wikimedia.org/2021/10/01/synchronising-wikidata-and-wikipedia-an-outreachy-project/)", this plugin does not appear to account for links to pages not in the Article space—see the "categories" "lists" and "templates" links there. To my mind the easiest thing would be to simply not show the popup for any link outside the Article space, since, in my opinion, the error message and link in the popup provide no benefit over a plain inline link.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/12046008/136275207-d4d00cbf-8842-4ae0-9f36-5bbb96585b72.png">

Thanks
Hugh

**Comment by stephanebisson** [comment]
Hi,  Support for other namespaces was implemented last month but the plugin still needs to be updated on the diff blog. Sorry for the inconvenience.

**Comment by hughlilly** [comment]
Oh, no problem; great to hear support has been added :)
