### ISSUE TITLE
`detectLinks` is not working

### ISSUE THREAD

**Issue by RudraSen2** [wikimedia/wikipedia-preview#167]
Hello,
This is my code:
```html
<html>
<head>
<title>WikiPedia Hoverable Description Preview</title>
<style>
.wmf-wp-with-preview {
  background-color: #eaf3ff;
  padding: 2px 2px 2px 2px;
  border-radius: 4px;
  border: solid 1px rgba(51, 102, 204, 0.48);
  cursor: pointer;
  line-height: normal;
}
.wmf-wp-with-preview::after {
  content: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBkPSJNMCAwaDIwdjIwSDB6Ii8+PHBhdGggZmlsbD0iIzM2QyIgZmlsbC1vcGFjaXR5PSIuNyIgZmlsbC1ydWxlPSJub256ZXJvIiBkPSJNMTAuNTU2IDEuMTExYy00LjYgMC04LjMzNCAzLjczMy04LjMzNCA4LjMzM3MzLjczNCA4LjMzNCA4LjMzNCA4LjMzNCA4LjMzMy0zLjczNCA4LjMzMy04LjMzNC0zLjczMy04LjMzMy04LjMzMy04LjMzM3ptLjgzMyAxMi41SDkuNzIydi01aDEuNjY3djV6bTAtNi42NjdIOS43MjJWNS4yNzhoMS42Njd2MS42NjZ6Ii8+PC9nPjwvc3ZnPg==");
  display: inline-block;
  vertical-align: middle;
  margin-left: 1px;
}
[dir='rtl'] .wmf-wp-with-preview::after {
  margin-left: auto;
  margin-right: 1px;
}
</style>
</head>
<body>
<h2>Custom Selector</h2>
<br>
<p class="content">
	You can learn about <span class="wikipedia">Chat</span> and <span class="wikipedia">Chien</span>, <span class="wikipedia">Virtual Machine</span> <span class="wikipedia">Apple Inc</span> from Wikipedia.
</p>
<br>
<h2>Detect Wiki Links</h2>
<br>
<p class="content">
	You can learn about <a href="https://en.wikipedia.org/wiki/Chat">Chat</a> and <a href="https://en.wikipedia.org/wiki/Chien">Chien</a> and <a href="https://en.wikipedia.org/wiki/Virtual_machine">Virtual machine</a> from Wikipedia.
</p>
<div class="popup-container"></div>
<script type="text/javascript" src="https://unpkg.com/wikipedia-preview@latest/dist/wikipedia-preview.production.js"></script>
<script type="text/javascript">
  wikipediaPreview.init({
  detectLinks: true,
  root: document.querySelector('.content'),
  selector: '.wikipedia',
  })
</script>
</body>
</html>
```

You see there are two examples - the first is the text one which is working fine but the second one which is the link one, is not working. Please fix. Any help is appreciated.

**Comment by hueitan** [comment]
You can either 

(1) wrap two contents into one container

or

(2) having two content containers

```html
<p class="content1"> ... </p>
<p class="content2"> ... </p>

<script>
  wikipediaPreview.init({
    detectLinks: true,
    root: document.querySelector('.content1'),
    selector: '.wikipedia',
  })
  wikipediaPreview.init({
    detectLinks: true,
    root: document.querySelector('.content2'),
    selector: '.wikipedia',
  })
</script>
```

**Comment by rahulX001** [comment]
Sir, I want to work on this issue , please assign me .

**Comment by umangutkarsh** [comment]
Is this issue resolved?

**Comment by umangutkarsh** [comment]
> You can either
> 
> (1) wrap two contents into one container
> 
> or
> 
> (2) having two content containers
> 
> ```
> <p class="content1"> ... </p>
> <p class="content2"> ... </p>
> 
> <script>
>   wikipediaPreview.init({
>     detectLinks: true,
>     root: document.querySelector('.content1'),
>     selector: '.wikipedia',
>   })
>   wikipediaPreview.init({
>     detectLinks: true,
>     root: document.querySelector('.content2'),
>     selector: '.wikipedia',
>   })
> </script>
> ```

Or is this the only alternative?^

**Comment by stephanebisson** [comment]
This issue is not resolved. You can use the workaround mentioned above (call init twice) or call it once with a root element higher up in the DOM that includes all the elements that should have aa preview. Note that if you don't specify the `root` option it uses the whole document.

Volunteer contributions are always welcome. I have filed a task with the team responsible but I don't know how it will get prioritized.

**Comment by umangutkarsh** [comment]
> This issue is not resolved. You can use the workaround mentioned above (call init twice) or call it once with a root element higher up in the DOM that includes all the elements that should have a preview. Note that if you don't specify the `root` option it uses the whole document.
> 
> Volunteer contributions are always welcome. I have filed a task with the team responsible but I don't know how it will get prioritized.

Okay, will check it and get back to you.

**Comment by umangutkarsh** [comment]
> This issue is not resolved. You can use the workaround mentioned above (call init twice) or call it once with a root element higher up in the DOM that includes all the elements that should have a preview. Note that if you don't specify the `root` option it uses the whole document.
> 
> Volunteer contributions are always welcome. I have filed a task with the team responsible but I don't know how it will get prioritized.

Hey @stephanebisson , I tried your approach of 'calling init twice', and the `detectLinks` is working. 
If anything else is needed please let me know.

**Comment by Beingadnan** [comment]
//Please replace 1.0.0 with the actual version you want to use.
<script type="text/javascript" src="https://unpkg.com/wikipedia-preview@1.0.0/dist/wikipedia-preview.production.js"></script>

// Move the script block for initializing the wikipediaPreview after the inclusion of the library and at the end of the HTML body. This ensures that the DOM is fully loaded before the script runs.
<script type="text/javascript">
  wikipediaPreview.init({
  detectLinks: true,
  root: document.querySelector('.content'),
  selector: '.wikipedia',
  })
</script>
