### ISSUE TITLE
Init with popupContainer results in Error: Uncaught (in promise): TypeError: e.appendChild is not a function

### ISSUE THREAD

**Issue by tarekeldeeb** [wikimedia/wikipedia-preview#182]
1. Installed the package through npm (v1.9)
2. Tried to run the example
3. Module loads and init function is called
4. Get an error:
```
main.ts:12 ERROR Error: Uncaught (in promise): TypeError: e.appendChild is not a function
TypeError: e.appendChild is not a function
    at jd (wikipedia-preview.js:4661:108)
```

**Comment by hueitan** [comment]
Hi @tarekeldeeb can you post your entire script including <script> and html, better if you have the demo site so we can check what's the issue there?

**Comment by hueitan** [comment]
I am closing this ticket, as I believe the issue has been fixed in a later commit. Please feel free to reopen this if you encounter the same problem again.
