### ISSUE TITLE
How to make link detection work in combination with VueJS3?

### ISSUE THREAD

**Issue by doebi** [wikimedia/wikipedia-preview#184]
Hi, I successfully embedded this snippet in my Vue3 application and invoke from within my applicaiton. But no matter how I configure the call to `init()` it does not find any links at all.

The debugger reports the correct configuration, and I am able to verify it manually, but it still does not detect any links:

![2024-01-20_15-47](https://github.com/wikimedia/wikipedia-preview/assets/1591457/8f28f04a-e995-44aa-a18e-6f600383fdc0)

Any hint what I might be missing here?

**Comment by hueitan** [comment]
have you set `detectLinks` to `true` in your `init()`?

**Comment by hueitan** [comment]
Close the issue for now, but feel free to reopen it if you need further assistance.
